smol-rs/async-channel

Cargo.toml, src/lib.rs
I saw that this crate did not have an `is_closed` method to check whether a channel is closed. This seemed rather trivial to implement - simply check whether the underlying queue is closed. However, looks can be deceiving, and I may have missed something! Please let me know if this is the case. I also bumped the version number from 1.2.0 to 1.3.0 to reflect the addition. Again, please let me know if you want this to be undone.
=> Add is_closed method

src/lib.rs, tests/bounded.rs, tests/unbounded.rs
Closes #18.
A few questions:
1) Is `Ordering::Relaxed` ok for this? I assume so since we're not coordinating anything, but I'm not an expert on this.
2) Any other test cases I should add in?
=> Add receiver_count and sender_count methods

src/lib.rs
=> impl FusedStream for Receiver

Cargo.toml, src/lib.rs
Closes https://github.com/smol-rs/async-channel/issues/22. cc/ @taiki-e I'm pretty sure the `pin-project-lite` impls here aren't needed, but my brain is too mush to think of how to do it using the pin-utils variants. Thanks!
=> Add `Send` and `Recv` futures

README.md, src/lib.rs
Without it, when I read documentation I thought that each message is copied for each consumer.
=> Added in docs main work principle of channel

src/lib.rs
In https://docs.rs/concurrent-queue/1.2.2/concurrent_queue/enum.PopError.html states that PopError::Closed only applies when it is empty **and** closed. 
Ideally, the documentation phrase should be "If the channel is empty, this method returns an error." because "empty, or empty and closed" can be reduced to "empty" but in order to specify both error types, I left it as "empty, or empty and closed".
This took some hours for me to check if the library was doing what I was expecting it to do. I hope this change saves this time to future readers of the documentation.
=> Fix documentation sentence

src/lib.rs, tests/bounded.rs, tests/unbounded.rs
As per discussion in smol-rs/async-lock#25, I have added `send_blocking` and `recv_blocking` methods to the `Sender` and `Receiver` structures, respectively. In order to reduce code duplication, I implemented this by parameterizing the logic found in the `Send` and `Recv` futures using a trait that either `poll`s the `EventListener` or calls `wait` on it.
Various things I left up in the air:
- I added private `wait()` methods on `Send` and `Recv` that use the blocking strategy to poll the future to completion. Should these be public?
- `Recv` currently implements `Stream`. It could also implement `Iterator` using a similar strategy to how I implemented blocking for the main methods. I decided against it, since `StreamExt` and `Iterator` share many method names which could be confused. Is …
=> Add blocking functionality to channels

Cargo.toml, src/lib.rs, tests/bounded.rs
Fixes https://github.com/smol-rs/async-channel/issues/45.
This is mostly similar to PR https://github.com/smol-rs/async-channel/pull/16 by another author, but its motivation is correctness rather than the purported performance advantage. Differences with PR https://github.com/smol-rs/async-channel/pull/16:
- it adds correctness tests for the case of forgotten sender and forgotten receiver,
- the commit is based on 1.7.0,
- the listener is not discarded when the future completes: in my understanding this would only help in the rare case where a sender/receiver completes due to a spurious wake-up (without consuming its notification); if my understanding is correct, I would say that the fixed cost of the extra conditional does not carry its weight.
I have made some benchmarking in various …
=> Prevent deadlock if sender/receiver is forgotten

src/lib.rs, tests/bounded.rs, tests/unbounded.rs
`tokio` recently added weak senders to its MPSC channel, and I thought that it was a pretty good idea. This PR adds a weak sender and receiver to this crate.
=> Add weak sender and receiver

.github/workflows/ci.yml, Cargo.toml, src/lib.rs, tests/bounded.rs, tests/unbounded.rs
Testing to make sure that `event-listener v3.0.0` actually works before we release smol-rs/event-listener#58
=> Bump to event-listener v3.0.0

.github/workflows/ci.yml, Cargo.toml, src/lib.rs, tests/bounded.rs, tests/unbounded.rs
This commit allows async-channel to be used fully in web environments
=> Add explicit web support

Cargo.toml, src/lib.rs
=> Port to event-listener v5.0.0

src/lib.rs, tests/bounded.rs
Closes #44 by adding a "force_send" method. This method can replace an
existing element in the list, in which case that element is returned.
This can be used to make "limited capacity" channels.
=> Add a force send function

Cargo.toml, src/lib.rs
Avoid needing to keep both event-listener and event-listener-strategy in sync by just relying on the reexport from event-listener-strategy. Should be a non-breaking change, since all of these changes should be semver compatible.
=> Use the reexported event-listener from event-listener-strategy

.github/workflows/ci.yml, Cargo.toml
Fixes #92
This also adds a check to CI to detect such a problem.
=> Update minimal concurrent-queue version to 2.5

src/lib.rs
I am porting some code from flume to async_channel, and this is one fn that I am sorely missing.
The implementation seems to be quite simple.
=> Add a fn to check if two senders or two receivers use the same channel

.github/workflows/ci.yml, src/lib.rs
See the first commit and https://github.com/smol-rs/.github/pull/1 for reusable workflows.
And see the second commit for CI failure.
=> ci: Use reusable workflows for fmt and security_audit & fix CI failure

.github/workflows/ci.yml, Cargo.toml, src/lib.rs
This lets users use this crate on targets that don't support atomics.
`cargo check --no-default-features --target thumbv6m-none-eabi` Fails on main.
But `cargo check --no-default-features --target thumbv6m-none-eabi --features portable-atomic,portable-atomic/fallback,portable-atomic/critical-section` passes on this PR.
This is blocking work in dependent PRs, for example, see [here](https://github.com/bevyengine/bevy/actions/runs/14090648644/job/39466542651?pr=18525).
=> Support portable atomic

src/lib.rs
Trivial fix. The original description was likely copied from `send_blocking`.
=> Fix description of `recv_blocking`

src/lib.rs, tests/bounded.rs
This adds `Sender::closed()` similar to `tokio::sync::mpsc::Sender::closed()` ([link](https://docs.rs/tokio/latest/tokio/sync/mpsc/struct.Sender.html#method.closed)).
=> Add Sender::closed future
